server:
  port: 8683

spring:
  datasource:
    url: jdbc:h2:mem:database
    driverClassName: org.h2.Driver
    username: user
    password: pass
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
